stages:
  #- build
  #- test
  - test_without_build

build:
  stage: build
  services:
    - docker:dind
  image: docker:git
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - >-
      docker build --pull
      --build-arg PROJECT_GIT_VERSION=$(git describe --tags --always)
      -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - docker-builder
  except:
    - /^wip[\/_-].+$/

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script: []
  script:
    - pytest
  dependencies: []
  tags:
    - docker
  except:
    - /^wip[\/_-].+$/

test_without_build:
  stage: test_without_build
  image: python3.6
  before_script: []
  script:
    - pip install -r requirements.txt
    - pytest
  dependencies: []
  tags:
    - docker
  except:
    - /^wip[\/_-].+$/
