stages:
  - test

test:
  stage: test
  image: python:3.6
  before_script: []
  script:
    - pip install -r requirements.txt
    - pytest --html=report.html
  dependencies: []
  tags:
    - docker
  except:
    - /^wip[\/_-].+$/
  artifacts:
    expire_in: 7 days
    paths:
      - report.html