stages:
  - test

test:
  stage: test
  image: python:3.6
  before_script: []
  script:
    - pip install -r requirements.txt
    - pytest --html=report.html
  dependencies: []
  tags:
    - docker
  except:
    - /^wip[\/_-].+$/
html:
  script: report.html
  artifacts:
    paths:
    - report.html
    expire_in: 1 week
